### ISSUE TITLE
templates for continuous integration and git-hooks

### ISSUE THREAD

**Issue by Remi-Gau** [florianschanda/miss_hit#152]
A couple of template files users could add to their repo or their .git/hook folder to make sure that their code is up to their standards before committing / pushing / merging.

For continuous integration:
- [x] github action
- [x] travis

For git hooks
- [x] pre-commit hook
- [x] pre-push hook

**Comment by florianschanda** [comment]
@Remi-Gau: please do open a PR for the travis stuff, since I am very unfamiliar with it. That said, since the stuff you linked is pretty simple I can make a stab at my own version. But some comments on the linked config:
* Ideally clone the latest release, not master (I do try to keep things non-broken, but it's not guaranteed)
* I suppose for that I need to have a `stable` branch :)
* I was thinking of putting this into `doc` and describe it in https://florianschanda.github.io/miss_hit/configuration.html since that document will/should contain everything about configuring and setting up miss_hit for your project

**Comment by florianschanda** [comment]
Also, in your opinion, what would you put in the pre-commit hook, and what would you put in the pre-push hook?

I can see two scenarios:

### 1
Pre-commit:
* mh_style --fix

Post-commit:
* mh_style
* mh_metric --ci

### 2
Pre-commit:
* mh_style --fix
* mh_metric --ci

Post-commit
* Nothing

**Comment by Remi-Gau** [comment]
> @Remi-Gau: please do open a PR for the travis stuff, since I am very unfamiliar with it. That said, since the stuff you linked is pretty simple I can make a stab at my own version. But some comments on the linked config:
> 
>     * Ideally clone the latest release, not master (I do try to keep things non-broken, but it's not guaranteed)
> 
>     * I suppose for that I need to have a `stable` branch :)
> 
>     * I was thinking of putting this into `doc` and describe it in https://florianschanda.github.io/miss_hit/configuration.html since that document will/should contain everything about configuring and setting up miss_hit for your project

Yup I am about to start some sort of template repo for matlab analysis, I would use that to test those config files for travis and github actions.

The thing is that I have some experiments to prepare for next week, so don't expect a first PR before the end of next week. :running_man: 

Good point on using on a release for those CI things.

Good idea about having this in the doc. :smile: :rocket:

**Comment by Remi-Gau** [comment]
> Also, in your opinion, what would you put in the pre-commit hook, and what would you put in the pre-push hook?
> 
> I can see two scenarios:
> ### 1
> 
> Pre-commit:
> 
>     * mh_style --fix
> 
> 
> Post-commit:
> 
>     * mh_style
> 
>     * mh_metric --ci
> 
> 
> ### 2
> 
> Pre-commit:
> 
>     * mh_style --fix
> 
>     * mh_metric --ci
> 
> 
> Post-commit
> 
>     * Nothing

Slight preference for scenario one, as it allows you to commit some code that you then get some metric info about so you can eventually refactor and to improve things.

 I like to try to keep first draft and refactoring separated. But maybe that's just me. 

What do you think ?

**Comment by Remi-Gau** [comment]
Started a quick and dirty repo to design a matlab analysis template.
https://github.com/Remi-Gau/template_matlab_analysis/issues/1

Will create a the templates for the linter there and then make a PR on this repo. Is that good with you @florianschanda ?

**Comment by florianschanda** [comment]
Sounds good, yeah! I will try and write some more documentation soon!

**Comment by Remi-Gau** [comment]
hey @florianschanda 

This could be a template for a `.travis.yml`. Very light weight but gets the job done

```
# Travis CI (https://travis-ci.org/)
# This will only work on your repo if you have an account on travis and you
# have set it up to run continuous integration on this this repo

# Linux distribution (bionic beaver)
dist: bionic

# Language and version
language: python
python:
  - "3.6" # current default Python on Travis CI

cache:
  apt: true # only works with Pro version

# Install the miss_hit linter
before_install:
  - pip3 install miss_hit

# Lists all the tasks we will do 
jobs:
  include:
    - name: "miss_hit: checking code quality"
      script: mh_metric . --ci
    - name: "miss_hit: checking code style"
      script: mh_style .
```

**Comment by Remi-Gau** [comment]
And this would be the template for a github action

```
name: miss_hit

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 1

    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install install miss_hit

    - name: Miss_hit code quality
      run: |
        mh_metric . --ci

    - name: Miss_hit code style
      run: |
        mh_style .
```
